### ISSUE TITLE
Fix Mr.X button 😅

### ISSUE THREAD

**Issue by AB-san** [sairish2001/makesmatheasy#2368] opened 2021-05-12 12:36 UTC
## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

![image](https://user-images.githubusercontent.com/71064674/117975810-b32eb080-b34c-11eb-92d0-b6e5a2389577.png)

i wud like to fix the bug

**Comment by RaveenaBhasin** [comment] 2021-05-12 12:50
@AB-san I think I have fixed the bug unknowingly in my latest PR. Once it will be merged kindly check if the problem is solved or not.

**Comment by AB-san** [comment] 2021-05-12 13:15
> @AB-san I think I have fixed the bug unknowingly in my latest PR. Once it will be merged kindly check if the problem is solved or not.

@RaveenaBhasin  are you talkin about #2342 ?

**Comment by AB-san** [comment] 2021-05-12 13:51
> @AB-san I think I have fixed the bug unknowingly in my latest PR. Once it will be merged kindly check if the problem is solved or not.

No, @RaveenaBhasin this bug is not resolved in #2329 
this bug has arise bcoz same tag id tag "#mi" is used for two buttons

**Closed** 2021-05-12 19:49 UTC
Labels: GSSOC21, Level0, bug
