### ISSUE TITLE
Sum of n terms of H.P

### ISSUE THREAD

**Issue by shrishti-c** [sairish2001/makesmatheasy#1281] opened 2021-04-20 17:31 UTC
calculator to calculate sum of n terms of H.P

**Comment by shonali2600** [comment] 2021-04-22 04:57
I would like to work on this issue, please assign it to me.

**Comment by sairish2001** [comment] 2021-04-23 19:00
Go ahead
Deadline 29 April,2021

**Comment by shrishti-c** [comment] 2021-04-24 03:37
@sairish2001 This issue has been opened by me. It should be assigned on First Come first serve basis na?

**Comment by shonali2600** [comment] 2021-04-24 07:24
@shrishti-c , I'm so sorry, I didn't know that you too are the participant and you opened this issue because you wanted to work on this. One thing I would like to suggest you that you should ask for the assignment of the issue along with the creation. That will be clear to all the other participants that you are a participant and want to work on this.
I'll also keep this in my mind to ask the creator of the issue is he/she a participant🙂

**Comment by shrishti-c** [comment] 2021-04-24 08:43
No worries. Have this issue as my contribution for ur higher score. ;) BTW, you can always check for the author of the issue.  You won't have to ask other as currently everyone is GSSOC participant.

**Comment by shonali2600** [comment] 2021-04-24 09:11
@shrishti-c , you got me wrong actually, Some times the Project admin and mentors too create issues for the participants, and I don't know who are the other maintainers of this project, I know only @sairish2001 as PA. And If I talk about the contribution then the contribution is mine, you created the issue only, @sairish2001 has already cleared this thing in the Discord itself.

@sairish2001, I'm a beginner this is the first time I'm participating in any open source program, I've not much idea about anything here, If I am wrong anywhere please assign this issue to her.

**Comment by shrishti-c** [comment] 2021-04-24 09:21
@shonali2600 Broooo... Chill...It's just a issue. I already have many issues assigned to me. Moreover you have already made a PR for this issue, so why to work on same thing twice yaarr.  

PS: I'm beginner too!!!

**Closed** 2021-04-24 16:20 UTC
Labels: GSSOC21, Level3
